version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=tlu_management
      - DB_USER=tuank
      - DB_PASS=Tuank@1994
    depends_on:
      - db

  db:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_DB=tlu_management
      - POSTGRES_USER=tuank
      - POSTGRES_PASSWORD=Tuank@1994
